### ISSUE TITLE
syslog-ng example config

### ISSUE THREAD

**Issue by k0nsl** [ekanite/ekanite#58]
Your syslog-ng example configuration is invalid. I don't know the correct configuration myself, just that it isn't correct and/or valid.

**Comment by otoolep** [comment]
Thanks. Let me double-check it. I

**Comment by k0nsl** [comment]
@otoolep:

Hi, you're welcome! I found out by testing it on one of my virtual machines. Which OS did you use while successfully running syslog-ng with the provided configuration that is located in this repository? I tried on Debian 8 and it does not work: the syntax is wrong (line 5, I think). I can re-install and capture the error, but I cannot do that exactly now due to other commitments.

**Comment by otoolep** [comment]
I don't see anything wrong with the config. I am following this reference:

https://www.loggly.com/docs/syslog-ng-manual-configuration/

**Comment by otoolep** [comment]
And others appear to be using my example fine. Please check that your config has been correctly copied from the example.

Can you show me your config?

**Comment by k0nsl** [comment]
@otoolep: I don't have the configuration anymore, as I purged it all.

I will try the example on another box today and see how it fares.

**Comment by otoolep** [comment]
No updates here.
