### ISSUE TITLE
Corrupted searching when shard number > 10

### ISSUE THREAD

**Issue by aclisp** [ekanite/ekanite#79]
Hi, 

I'm using goleveldb backend, setting shards = 16. 

The problem can be reproduced by these steps:
1. start ekanite
2. send some logs to it.
3. search looks fine.
4. restart ekanite
5. search again with the same query. It shows a lots of empty items.

After digging into the code, some suspects are:
* ekanite does not call engine.Close() when quitting, so the underlining KVStore is not properly closed.
* When ekanite restart from a non-empty data dir, It loads the shards in alphabetical order, and add them into IndexAlias in the same order. It may be the cause when shard number > 10, so it loads actually 0, 1, 10, 11, ...

A quit test by setting shards = 8, the problem gone.

**Comment by otoolep** [comment]
Thanks for the report @aclisp -- I'll take a look.

**Comment by otoolep** [comment]
Oh -- you're using the goleveldb backend? I can't really investigate since I have never used that storage engine. While it should work, I can't speak to its quality.

>ekanite does not call engine.Close() when quitting, so the underlining KVStore is not properly closed.

You're right, it doesn't. I'll fix that up. However, if goleveldb can't deal with a hard shutdown (I would be shocked if it couldn't) you have bigger problems. I can't guarantee someone won't, say, send SIGKILL to Ekanite.

**Comment by otoolep** [comment]
Engine closed on exit: https://github.com/ekanite/ekanite/pull/81

**Comment by otoolep** [comment]
>>When ekanite restart from a non-empty data dir, It loads the shards in alphabetical order, and add them into IndexAlias in the same order. It may be the cause when shard number > 10, so it loads actually 0, 1, 10, 11, ... 

Damn, you're right, not good. Fortunately the default number of shards is 4, so hopefully not too many people have hit this.

**Comment by otoolep** [comment]
https://github.com/ekanite/ekanite/pull/82 will fix shard naming. However this will make versions of this fix incompatible with earlier versions, unless the shards are manually renamed on disk.

**Comment by otoolep** [comment]
Thanks for spotting the bugs @aclisp -- I have fixed them in master, but if you were running with shard counts greater than 9, you will need to manually rename your shards (stop Ekanite first). Or simply try a new system after building top-of-tree.

**Comment by otoolep** [comment]
As for the corrupted searches, I suggest you try with the BoltDB backend (bleve's default) and see if you see any problems. If not, but you do see them with goleveldb, then it's clearly specific to that engine. I have not done any testing with goleveldb however.

I'm closing this issue now, but please open a new ticket if hit anymore issues.
