### ISSUE TITLE
steps to diagnose lack of content in logs

### ISSUE THREAD

**Issue by themightychris** [ekanite/ekanite#98]
I've just deployed an ekanite instance, and am not seeing any log data in the system. I'm not sure whether the issue is the configuration of my client, its connectivity to ekanite, or ekanite's ability to parse the log entries being sent to it.

I've verified that the host/port for ekanite is reachable from the client system, and enabled the `-diag` endpoint, but without documentation showing what the diagnostic JSON _should_ look like it's hard to know what to look for

Here's what the initial chunk of the diagnostic output looks like:

```json
{
  "bleve": {
    "bootDuration": 12030,
    "indexes": {}
  },
  "cmdline": [
    "/usr/local/bin/ekanited",
    "-datadir",
    "/data/index",
    "-tcp",
    ":5514",
    "-queryhttp",
    ":8080",
    "-retention",
    "168h",
    "-diag",
    ":9951"
  ],
  "ekanite": {},
  "engine": {
    "queriesRx": 5
  },
  "input": {},
  "memstats": {
    "Alloc": 1269032,
    "TotalAlloc": 1269032,
    "Sys": 4165632,
    "Lookups": 38,
    "Mallocs": 8128,
    "Frees": 417,
    "HeapAlloc": 1269032,
    "HeapSys": 2686976,
    "HeapIdle": 737280,
    "HeapInuse": 1949696,
    "HeapReleased": 0,
    "HeapObjects": 7711,
    "StackInuse": 458752,
    "StackSys": 458752,
    "MSpanInuse": 25080,
    "MSpanSys": 32768,
    "MCacheInuse": 3472,
    "MCacheSys": 16384,
    "BuckHashSys": 3055,
    "GCSys": 169984,
    "OtherSys": 797713,
    "NextGC": 4473924,
    "LastGC": 0,
    "PauseTotalNs": 0,
    "PauseNs": [
      0,
      0,
      0,
```

After than its a ton of 0 lines for `PauseNs`, and then `PauseEnd` with a ton of 0s, and then a bunch of memory information objects

Is `"input": {},` significant? The key thing I'm trying to determine at this point is whether ekanite is receiving any messages, and then how many of those it's successfully parsing. Is the empty `input` section telling me it hasn't received anything? Would it look any different if ekanite was receiving messages but failing to parse them? If ekanite was receiving messages but failing to parse them, would I be able to get a look at what the messages it's receiving look like anywhere and/or what the parse error is?

**Comment by otoolep** [comment]
Hi -- as mentioned in the README (though it's at the bottom, I admit) this project is not actively maintained.

https://github.com/ekanite/ekanite/issues/98

I'm going to archive it to prevent any future confusion.
